export const ErrorCodes = {
  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  AUTH_EMAIL_TAKEN: 'AUTH_EMAIL_TAKEN',
  AUTH_UNAUTHORIZED: 'AUTH_UNAUTHORIZED',
  AUTH_TOKEN_EXPIRED: 'AUTH_TOKEN_EXPIRED',
  AUTH_TOKEN_INVALID: 'AUTH_TOKEN_INVALID',
  AUTH_REFRESH_INVALID: 'AUTH_REFRESH_INVALID',
  AUTH_REFRESH_REUSE: 'AUTH_REFRESH_REUSE',
  AUTH_INVALID_ORIGIN: 'AUTH_INVALID_ORIGIN',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  NOT_FOUND: 'NOT_FOUND',
  CATALOG_NOT_FOUND: 'CATALOG_NOT_FOUND',
  LIBRARY_TRACK_NOT_FOUND: 'LIBRARY_TRACK_NOT_FOUND',
  PLAYLIST_NOT_FOUND: 'PLAYLIST_NOT_FOUND',
  PLAYLIST_TRACK_NOT_FOUND: 'PLAYLIST_TRACK_NOT_FOUND',
  PLAYLIST_REORDER_MISMATCH: 'PLAYLIST_REORDER_MISMATCH',
  PLAYLIST_CONFLICT: 'PLAYLIST_CONFLICT',
  FAVORITE_NOT_FOUND: 'FAVORITE_NOT_FOUND',
  FAVORITE_AMBIGUOUS: 'FAVORITE_AMBIGUOUS',
  HISTORY_TRACK_NOT_FOUND: 'HISTORY_TRACK_NOT_FOUND',
  HISTORY_IDEMPOTENCY_MISMATCH: 'HISTORY_IDEMPOTENCY_MISMATCH',
  HISTORY_DURATION_INVALID: 'HISTORY_DURATION_INVALID',
  LYRICS_NOT_FOUND: 'LYRICS_NOT_FOUND',
  LYRICS_PROVIDER_ERROR: 'LYRICS_PROVIDER_ERROR',
  STREAM_TRACK_UNAVAILABLE: 'STREAM_TRACK_UNAVAILABLE',
  STREAM_ASSET_UNAVAILABLE: 'STREAM_ASSET_UNAVAILABLE',
  STREAM_QUALITY_UNAVAILABLE: 'STREAM_QUALITY_UNAVAILABLE',
  STREAM_FORMAT_UNSUPPORTED: 'STREAM_FORMAT_UNSUPPORTED',
  TRACK_NOT_FOUND: 'TRACK_NOT_FOUND',
  SOURCE_NOT_FOUND: 'SOURCE_NOT_FOUND',
  SOURCE_UNAVAILABLE: 'SOURCE_UNAVAILABLE',
  MEDIA_ACCESS_DENIED: 'MEDIA_ACCESS_DENIED',
  PREFERENCES_CONFLICT: 'PREFERENCES_CONFLICT',
  ADMIN_FORBIDDEN: 'ADMIN_FORBIDDEN',
  UPLOAD_INVALID_TYPE: 'UPLOAD_INVALID_TYPE',
  UPLOAD_TOO_LARGE: 'UPLOAD_TOO_LARGE',
  UPLOAD_NOT_FOUND: 'UPLOAD_NOT_FOUND',
  UPLOAD_FORBIDDEN: 'UPLOAD_FORBIDDEN',
  UPLOAD_OBJECT_MISSING: 'UPLOAD_OBJECT_MISSING',
  UPLOAD_CHECKSUM_MISMATCH: 'UPLOAD_CHECKSUM_MISMATCH',
  UPLOAD_SIZE_MISMATCH: 'UPLOAD_SIZE_MISMATCH',
  UPLOAD_EXPIRED: 'UPLOAD_EXPIRED',
  UPLOAD_CONFLICT: 'UPLOAD_CONFLICT',
  INGESTION_NOT_READY: 'INGESTION_NOT_READY',
  PUBLISH_NOT_READY: 'PUBLISH_NOT_READY',
  IMPORT_NOT_FOUND: 'IMPORT_NOT_FOUND',
  IMPORT_FORBIDDEN: 'IMPORT_FORBIDDEN',
  IMPORT_NOT_READY: 'IMPORT_NOT_READY',
  IMPORT_AMBIGUOUS_MATCH: 'IMPORT_AMBIGUOUS_MATCH',
  IMPORT_DUPLICATE_CHECKSUM: 'IMPORT_DUPLICATE_CHECKSUM',
  IMPORT_CONFLICT: 'IMPORT_CONFLICT',
  TRACK_IN_USE: 'TRACK_IN_USE',
  RATE_LIMITED: 'RATE_LIMITED',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  NOT_READY: 'NOT_READY',
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];

export class AppError extends Error {
  readonly statusCode: number;
  readonly code: ErrorCode;
  readonly expose: boolean;

  constructor(statusCode: number, code: ErrorCode, message: string, expose = true) {
    super(message);
    this.name = 'AppError';
    this.statusCode = statusCode;
    this.code = code;
    this.expose = expose;
  }
}

export interface ErrorEnvelope {
  code: string;
  message: string;
  request_id: string;
}

export function errorEnvelope(code: string, message: string, requestId: string): ErrorEnvelope {
  return { code, message, request_id: requestId };
}
